name = "ExtrinsicGJMSOperators"
version = "0.1.0"
defaultTargets = ["extrinsicgjmsoperators"]

[[lean_lib]]
name = "ExtrinsicGJMSOperators"

[[lean_exe]]
name = "extrinsicgjmsoperators"
root = "Main"
